export { default as AvenirRomanEot } from "./Avenir-Roman.eot"
export { default as AvenirRomanWoff2 } from "./Avenir-Roman.woff2"
export { default as AvenirRomanWoff } from "./Avenir-Roman.woff"
export { default as AvenirRomanTtf } from "./Avenir-Roman.ttf"
export { default as AvenirRomanSvg } from "./Avenir-Roman.svg"

export { default as AvenirBlackEot } from "./Avenir-Black.eot"
export { default as AvenirBlackWoff2 } from "./Avenir-Black.woff2"
export { default as AvenirBlackWoff } from "./Avenir-Black.woff"
export { default as AvenirBlackTtf } from "./Avenir-Black.ttf"
export { default as AvenirBlackSvg } from "./Avenir-Black.svg"
